platform:ios, '13.0'
target 'QuickStart'
pod 'Ringcentral-Video-SDK', '~> 0.14.0'

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
        end
    end
end
